version: "3.9"
services:
  mongodb:
    image: mongo:7
    container_name: elib-mongodb-dev
    restart: unless-stopped
    ports:
      - "27017:27017"
    volumes:
      - mongodb-data:/data/db
    networks:
      - elib-dev-net

  redis:
    image: redis:7-alpine
    container_name: elib-redis-dev
    restart: unless-stopped
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data
    networks:
      - elib-dev-net

networks:
  elib-dev-net:
    driver: bridge

volumes:
  mongodb-data:
  redis-data:
