version: "3.9"
services:
  elib:
    image: iarpitchauhan/elibrary-api:staging
    container_name: elibrary-api
    restart: unless-stopped
    ports:
      - "3001:3001"
    env_file:
      - .env.staging
    depends_on:
      - redis
    networks:
      - elib-net

  redis:
    image: redis:7-alpine
    container_name: elib-redis
    restart: unless-stopped
    ports:
      - "6179:6179"
    volumes:
      - redis-data:/data
    networks:
      - elib-net

  prometheus:
    image: prom/prometheus:v2.52.0
    container_name: elib-prometheus
    restart: unless-stopped
    ports:
      - "9090:9090"
    volumes:
      - ./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml:ro
      - prometheus-data:/prometheus
    networks:
      - elib-net

  grafana:
    image: grafana/grafana:11.0.0
    container_name: elib-grafana
    restart: unless-stopped
    ports:
      - "3000:3000"
    volumes:
      - grafana-data:/var/lib/grafana
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=admin
    networks:
      - elib-net

  node-exporter:
    image: prom/node-exporter:v1.8.1
    container_name: elib-node-exporter
    restart: unless-stopped
    pid: host
    volumes:
      - /proc:/host/proc:ro
      - /sys:/host/sys:ro
      - /:/rootfs:ro
    command:
      - "--path.procfs=/host/proc"
      - "--path.sysfs=/host/sys"
      - "--path.rootfs=/rootfs"
    networks:
      - elib-net

networks:
  elib-net:
    driver: bridge

volumes:
  redis-data:
  prometheus-data:
  grafana-data:
