global:
  scrape_interval: 10s

scrape_configs:
  - job_name: "elib-api"
    static_configs:
      - targets: ["elib:3001"]
    scrape_interval: 5s
    metrics_path: /metrics
  - job_name: "node-exporter"
    static_configs:
      - targets: ["node-exporter:9100"]
